### ISSUE TITLE
The Australian

### ISSUE THREAD

**Issue by Frederikalan** [hankolsen/dn-paywall-remover#1]
Has stopped working with The Australian?  Was working fine.
Thanks for looking.
https://www.theaustralian.com.au/

**Comment by hankolsen** [comment]
Thank you for reporting the issue!
I have not tried The Australian before, but from what it looks like when I try it now, they also seem to have changed the way their paywall is built. Sorry about that.

**Comment by Frederikalan** [comment]
Thanks for checking it out, it used to work.

I cad without a Murdoch newspaper.

 

 

 

F,

  _____  

Frederik Alan-Smith | 76 / 200 Goulburn Street | Surry Hills | 2010 | 02 8041 2077 | 041 777 2909 |
